var config;
if (typeof(require) === 'undefined') {
    /* XXX: Hack to work around r.js's stupid parsing.
     * We want to save the configuration in a variable so that we can reuse it in
     * tests/main.js.
     */
    require = { config: function (c) { config = c; } };
}

require.config({
    baseUrl: 'src',
    paths: {
        "eventEmitter":                     "bower_components/eventEmitter",
        "eventie":                          "bower_components/eventie",
        "get-size":                         "bower_components/get-size",
        "get-style-property":               "bower_components/get-style-property",
        "google-code-prettify":             "bower_components/google-code-prettify/src/prettify",
        "imagesloaded":                     "bower_components/imagesloaded/imagesloaded",
        "jcrop":                            "bower_components/jcrop/js/jquery.Jcrop",
        "jquery":                           "bower_components/jquery/dist/jquery",
        "jquery.browser":                   "bower_components/jquery.browser/dist/jquery.browser",
        "jquery.anythingslider":            "bower_components/AnythingSlider/js/jquery.anythingslider",
        "jquery.chosen":                    "bower_components/chosen/chosen/chosen.jquery",
        "jquery.form":                      "bower_components/jquery-form/jquery.form",
        "jquery.fullcalendar":              "bower_components/fullcalendar/fullcalendar.min",
        "jquery.fullcalendar.dnd":          "bower_components/fullcalendar/lib/jquery-ui.custom.min",
        "jquery.placeholder":               "bower_components/jquery-placeholder/jquery.placeholder.min",
        "jquery.textchange":                "bower_components/jquery-textchange/jquery.textchange",
        "logging":                          "bower_components/logging/src/logging",
        "masonry":                          "bower_components/masonry/dist/masonry.pkgd",
        "matches-selector":                 "bower_components/matches-selector",
        "modernizr":                        "bower_components/modernizr/modernizr",
        "modernizr-csspositionsticky":      "bower_components/modernizr/feature-detects/css-positionsticky",
        "outlayer":                         "bower_components/outlayer",
        "parsley":                          "bower_components/parsleyjs/parsley",
        "parsley.extend":                   "bower_components/parsleyjs/parsley.extend",
        "patternslib.slides":               "bower_components/slides/src/slides",
        "photoswipe":                       "bower_components/photoswipe/dist/photoswipe",
        "photoswipe-ui":                    "bower_components/photoswipe/dist/photoswipe-ui-default",
        "photoswipe-template":              "../patternslib/src/pat/gallery/template",
        "pikaday":                          "bower_components/pikaday/pikaday",
        "prefixfree":                       "bower_components/prefixfree/prefixfree.min",
        "select2":                          "bower_components/select2/select2.min",
        "showdown":                         "bower_components/showdown/src/showdown",
        "showdown-github":                  "bower_components/showdown/src/extensions/github",
        "showdown-prettify":                "bower_components/showdown/src/extensions/prettify",
        "showdown-table":                   "bower_components/showdown/src/extensions/table",
        "spectrum":                         "bower_components/spectrum/spectrum",
        "text":                             "bower_components/requirejs-text/text",
        "tpl":                              "bower_components/requirejs-tpl-jcbrand/tpl",
        "tinymce":                          "bower_components/jquery.tinymce/jscripts/tiny_mce/jquery.tinymce",
        "underscore":                       "bower_components/underscore/underscore",
        "validate":                         "bower_components/validate/validate",

        // Calendar pattern
        "moment": "bower_components/moment/moment",
        "moment-timezone": "bower_components/moment-timezone/moment-timezone",
        "pat-calendar-moment-timezone-data": "../patternslib/src/pat/calendar/moment-timezone-data",

        // Core
        "pat-compat":               "../patternslib/src/core/compat",
        "pat-base":                 "../patternslib/src/core/base",
        "pat-date-picker":          "../patternslib/src/pat/date-picker/date-picker",
        "pat-depends_parse":        "../patternslib/src/lib/depends_parse",
        "pat-dependshandler":       "../patternslib/src/lib/dependshandler",
        "pat-htmlparser":           "../patternslib/src/lib/htmlparser",
        "pat-input-change-events":  "../patternslib/src/lib/input-change-events",
        "pat-jquery-ext":           "../patternslib/src/core/jquery-ext",
        "pat-logger":               "../patternslib/src/core/logger",
        "pat-parser":               "../patternslib/src/core/parser",
        "pat-mockup-parser":        "../patternslib/src/core/mockup-parser",
        "pat-registry":             "../patternslib/src/core/registry",
        "pat-remove":               "../patternslib/src/core/remove",
        "pat-store":                "../patternslib/src/core/store",
        "pat-url":                  "../patternslib/src/core/url",
        "pat-utils":                "../patternslib/src/core/utils",

        // Patterns
        "pat-ajax":                    "../patternslib/src/pat/ajax/ajax",
        "pat-autofocus":               "../patternslib/src/pat/autofocus/autofocus",
        "pat-autoscale":               "../patternslib/src/pat/auto-scale/auto-scale",
        "pat-auto-scale":               "../patternslib/src/pat/auto-scale/auto-scale",
        "pat-autosubmit":              "../patternslib/src/pat/auto-submit/auto-submit",
        "pat-auto-submit":              "../patternslib/src/pat/auto-submit/auto-submit",
        "pat-autosuggest":             "../patternslib/src/pat/auto-suggest/auto-suggest",
        "pat-auto-suggest":             "../patternslib/src/pat/auto-suggest/auto-suggest",
        "pat-breadcrumbs":             "../patternslib/src/pat/breadcrumbs/breadcrumbs",
        "pat-bumper":                  "../patternslib/src/pat/bumper/bumper",
        "pat-calendar":                "../patternslib/src/pat/calendar/calendar",
        "pat-carousel":                "../patternslib/src/pat/carousel/carousel",
        "pat-checkedflag":             "../patternslib/src/pat/checked-flag/checked-flag",
        "pat-checked-flag":             "../patternslib/src/pat/checked-flag/checked-flag",
        "pat-checklist":               "../patternslib/src/pat/checklist/checklist",
        "pat-chosen":                  "../patternslib/src/pat/chosen/chosen",
        "pat-clone":                   "../patternslib/src/pat/clone/clone",
        "pat-collapsible":             "../patternslib/src/pat/collapsible/collapsible",
        "pat-colour-picker":           "../patternslib/src/pat/colour-picker/colour-picker",
        "pat-depends":                 "../patternslib/src/pat/depends/depends",
        "pat-edit-tinymce":            "../patternslib/src/pat/edit-tinymce/edit-tinymce",
        "pat-equaliser":               "../patternslib/src/pat/equaliser/equaliser",
        "pat-expandable":              "../patternslib/src/pat/expandable-tree/expandable-tree",
        "pat-expandable-tree":         "../patternslib/src/pat/expandable-tree/expandable-tree",
        "pat-focus":                   "../patternslib/src/pat/focus/focus",
        "pat-form-state":              "../patternslib/src/pat/form-state/form-state",
        "pat-forward":                 "../patternslib/src/pat/forward/forward",
        "pat-gallery":                 "../patternslib/src/pat/gallery/gallery",
        "pat-grid":                    "../patternslib/src/pat/grid/grid",  // Hack, there's no grid jS, but we need for website bundler
        "pat-syntax-highlight":        "../patternslib/src/pat/syntax-highlight/syntax-highlight",
        "pat-image-crop":              "../patternslib/src/pat/image-crop/image-crop",
        "pat-inject":                  "../patternslib/src/pat/inject/inject",
        "pat-legend":                  "../patternslib/src/pat/legend/legend",
        "pat-markdown":                "../patternslib/src/pat/markdown/markdown",
        "pat-masonry":                 "../patternslib/src/pat/masonry/masonry",
        "pat-menu":                    "../patternslib/src/pat/menu/menu",
        "pat-modal":                   "../patternslib/src/pat/modal/modal",
        "pat-navigation":              "../patternslib/src/pat/navigation/navigation",
        "pat-notification":            "../patternslib/src/pat/notification/notification",
        "pat-placeholder":             "../patternslib/src/pat/placeholder/placeholder",
        "pat-selectbox":               "../patternslib/src/pat/selectbox/selectbox",
        "pat-skeleton":                "../patternslib/src/pat/skeleton/skeleton",
        "pat-slides":                  "../patternslib/src/pat/slides/slides",
        "pat-slideshow-builder":       "../patternslib/src/pat/slideshow-builder/slideshow-builder",
        "pat-sortable":                "../patternslib/src/pat/sortable/sortable",
        "pat-stacks":                  "../patternslib/src/pat/stacks/stacks",
        "pat-subform":                 "../patternslib/src/pat/subform/subform",
        "pat-switch":                  "../patternslib/src/pat/switch/switch",
        "pat-scroll":                  "../patternslib/src/pat/scroll/scroll",
        "pat-toggle":                  "../patternslib/src/pat/toggle/toggle",
        "pat-tooltip":                 "../patternslib/src/pat/tooltip/tooltip",
        "pat-validation":              "../patternslib/src/pat/validation/validation",
        "pat-zoom":                    "../patternslib/src/pat/zoom/zoom",
        "patterns":                    "patterns"
    },

    shim: {
        "jcrop":                        { deps: ["jquery"] },
        "jquery":                       { exports: ["jQuery"] },
        "jquery.anythingslider":        { deps: ["jquery"] },
        "jquery.chosen":                { deps: ["jquery"] },
        "jquery.fullcalendar.dnd":      { deps: ["jquery"] },
        "jquery.placeholder":           { deps: ["jquery"] },
        "jquery.textchange":            { deps: ["jquery"] },
        "parsley":                      { deps: ["jquery"] },
        "parsley.extend":               { deps: ["jquery"] },
        "select2":                      { deps: ["jquery"] },
        "spectrum":                     { deps: ["jquery"] },
        "tinymce":                      { deps: ["jquery"] },
        "showdown-github":              { deps: ["showdown"] },
        "showdown-prettify":            { deps: ["showdown", "google-code-prettify"] },
        "showdown-table":               { deps: ["showdown"] }
    },
});

if (typeof(require) === 'function') {
    require(["patterns"], function(patterns) {});
}
